# https://gist.github.com/benoitpetit/cbe19cdd369ec8c1e0defd245d91751f
version: '4.5'
services:

  # GITLAB
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-web
    hostname: 'gitlab-web'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-web.local'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'http://gitlab-web.local:5050'
        registry['enable'] = true
        gitlab_rails['registry_port'] = "5050"
        gitlab_rails['registry_host'] = "gitlab-web.local"
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      gitlab-network:
        aliases:
          - gitlab-web.local

  # RUNNER
  gitlab-runner1:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    depends_on:
      - gitlab-web
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network

networks:
  gitlab-network:
    name: gitlab-network